'use client';
import React,{useEffect,useState,useRef} from 'react';
import {supabase,configured,adminApi} from '../lib/supabase';
export function AdminAccess({children}:{children:React.ReactNode}) {
 const [allowed,setAllowed]=useState(false); const [session,setSession]=useState(false);
 const generation=useRef(0);
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [code,setCode]=useState('');
 const [factor,setFactor]=useState(''); const [qr,setQr]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 useEffect(()=>{let active=true; const check=async()=>{const version=++generation.current;const {data}=await supabase.auth.getSession();if(!active||version!==generation.current)return;setSession(!!data.session);setAllowed(false);if(data.session){try {await adminApi('/dashboard');if(active&&version===generation.current)setAllowed(true);}catch(e){if(active&&version===generation.current)setError((e as Error).message);}}};check();const {data:{subscription}}=supabase.auth.onAuthStateChange(()=>{generation.current++;setAllowed(false);setFactor('');setQr('');setCode('');setTimeout(check,0);});return()=>{active=false;generation.current++;subscription.unsubscribe();};},[]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;setPassword('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function setup(){setBusy(true);setError('');try{const {data,error}=await supabase.auth.mfa.listFactors();if(error)throw error;const verified=data.totp.find(f=>f.status==='verified');if(verified){setFactor(verified.id);}else{const pending=data.all.find(f=>f.factor_type==='totp' && f.status==='unverified');if(pending)await supabase.auth.mfa.unenroll({factorId:pending.id});const {data:newFactor,error}=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'KAZA Admin'});if(error)throw error;setFactor(newFactor.id);setQr(newFactor.totp.qr_code.replace(/^data:image\/svg\+xml;utf-8,/,''));}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function verify(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const {error}=await supabase.auth.mfa.challengeAndVerify({factorId:factor,code});if(error)throw error;setQr('');setCode('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!configured)return <main style={{padding:40}}>Configurá NEXT_PUBLIC_SUPABASE_URL y NEXT_PUBLIC_SUPABASE_ANON_KEY para iniciar el panel.</main>;
 if(allowed)return <><div style={{padding:8,background:'#102b37',color:'white',display:'flex',justifyContent:'space-between'}}>Administración protegida<button onClick={async()=>{setAllowed(false);await supabase.auth.signOut();}}>Cerrar sesión</button></div>{children}</>;
 return <main style={{maxWidth:440,margin:'70px auto',padding:24,fontFamily:'sans-serif'}}><h1>KAZA Administración</h1><p>Usá una cuenta autorizada y verificá el segundo factor.</p>{error&&<p role="alert" style={{color:'#a12828'}}>{error}</p>}{!session?<form onSubmit={login}><label>Correo<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username"/></label><label>Contraseña<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><button disabled={busy}>Iniciar sesión</button></form>:<><button disabled={busy} onClick={setup}>Configurar o verificar segundo factor</button>{qr&&<img alt="Escaneá este código con tu autenticador" width={220} height={220} src={`data:image/svg+xml;utf-8,${encodeURIComponent(qr)}`}/ >}{factor&&<form onSubmit={verify}><label>Código del autenticador<input inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required value={code} onChange={e=>setCode(e.target.value)}/></label><button disabled={busy}>Verificar</button></form>}<button onClick={()=>supabase.auth.signOut()}>Cambiar cuenta</button></>}</main>;
}
